### ISSUE TITLE
点击播放图标视频不会播放

### ISSUE THREAD

**Issue by tcqq** [onestravel/FiveFiveVideoPlayer#1]
在播放界面点击视频中间的播放图标，视频不会继续播放

**Comment by onestravel** [comment]
你好，这个问题已经解决，请使用1. 0. 3版本，如有其他问题，麻烦反馈给我，谢谢支持！！！



---原始邮件---
发件人: "tcqq"<notifications@github.com&gt;
发送时间: 2020年8月28日(周五) 中午11:53
收件人: "onestravel/FiveFiveVideoPlayer"<FiveFiveVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [onestravel/FiveFiveVideoPlayer] 点击播放图标视频不会播放 (#1)




 
在播放界面点击视频中间的播放图标，视频不会播放

**Comment by tcqq** [comment]
好的，谢谢

**Comment by tcqq** [comment]
@onestravel 手势调整视频进度的功能好像有点问题，如果当前的视频比较短，例如10秒，然后用手往右滑动一点，视频进度就直接从1到10了，希望可以优化下
